# Generated by Django 3.2.6 on 2021-08-09 21:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EmployeeApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employees',
            old_name='EmployeeeName',
            new_name='EmployeeName',
        ),
    ]
